#let type(s) = raw(s, lang: "kt")

#let KtBool = type("Boolean")
#let KtByte = type("Byte")
#let KtShort = type("Short")
#let KtInt = type("Int")
#let KtLong = type("Long")
#let KtChar = type("Char")
#let KtFloat = type("Float")
#let KtDouble = type("Double")
#let KtString = type("String")
#let KtUnit = type("Unit")
#let KtNothing = type("Nothing")

#let KtStar = type("*")

#let Any = type("Any")
#let Array(of) = type("Array<" + of.text + ">")
#let List(of) = type("List<" + of.text + ">")
#let MutableList(of) = type("MutableList<" + of.text + ">")
#let Pair(f, s) = type("Pair<" + f.text + ", " + s.text + ">")
#let Comparable(of) = type("Comparable<" + of.text + ">")
